spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: scott
    password: wym998051
  mvc:
    view:
      suffix: .html
      prefix: resources/templates/